name: Ensure clean Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ensure-clean-notebooks:
    uses: sgibson91/.github/.github/workflows/clean-notebook-outputs.yaml@main
