name: Validate JSON files

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.json"
  pull_request:
    branches:
      - main
    paths:
      - "**.json"

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install jsonschema
      - run: python validate_json.py
